images_target_dir: data/images
excel_files_target_dir: data/labels
image_betas_dir: data/image_betas
t_test_results_dir: data/t_test_results
t_test_roi_dir: data/t_test_roi
mds_dir: data/mds_dir
rdm_dir: data/rdm_dir

full_brain_data_dir: /media/harveylab/STORAGE1_NA/NSD/full_brain
stans_thesis_repo_data: /media/harveylab/storage2/stan-thesis/data/
mask_data_dir: mask
freesurfer_dir: /media/harveylab/storage2/stan-thesis/data/nsddata/freesurfer

coco_train_json_path: data/coco/instances_train2017.json
coco_val_json_path: data/coco/instances_val2017.json

nsd_coco_file_path: coco/nsd_coco.xlsx
nsd_labeled_subset_path: coco/nsd_full_coco.xlsx

nsd_labeled_subset_non_animals: nsd_full_non_animals.xlsx
nsd_labeled_subset_animals_humans: nsd_full_animals_humans.xlsx

nsd_negative_subset: animate_nonface/animate_non_face_filtered.xlsx
nsd_positive_subset: faces/faces_subset_filtered.xlsx

face_detection_results_path: face_detection_result.json

nsd_data_dir: /media/harveylab/storage2/stan-thesis/data
mask_subdir: mask
label_subdir: nsddata
conds_subdir: conditions
nsd_subdir: NSD

proj_dir: /media/harveylab/storage2/stan-thesis
betas_subdir: betas

subjects_to_analyze: [1, 2, 3, 7]
rois_to_analyze: { "1": 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6, "7": 7 }

gaussian_fit_results_dir: data/gaussian_results

# for dataset creation
nsd_samples_subjects_to_check: ["shared", "1"] # ['shared', '1', ..., '8']
