# Directories for storing processed data
directories:
  images_target_dir: data/images
  excel_files_target_dir: data/labels
  image_betas_dir: data/image_betas_stan
  t_test_results_dir: data/t_test_results
  t_test_roi_dir: data/t_test_roi
  mds_dir: data/mds/final
  rdm_dir: data/rdm/final
  gaussian_fit_results_dir: data/gaussian_results
  output_dir: data/output
  activations_dir: data/activations
  # matlab_masks_dir: data/matlab_masks

  distances_dir: data/distances

saved_results_paths:
  sample_repeatability_distances_pickle: sample_repeatability_distances.pkl
  sample_repeatability_distances_excel: sample_repeatability_distances.xlsx
  sample_repeatability_correlations_true_excel: sample_repeatability_correlations_true.xlsx
  sample_repeatability_correlations_null_excel: sample_repeatability_correlations_null.xlsx


  spearman_correlations_pickle: spearman_correlations.pkl
  spearman_correlations_excel: spearman_correlations.xlsx

  permutation_analysis_excel: permutation_analysis.xlsx

# NSD data locations
nsd_data:
  nsddata_responses_tsv_dir: data/nsddata_tsv
  nsddata_betas_dir: /media/harveylab/STORAGE1_NA/NSD/nsddata_betas
  full_brain_data_dir: /media/harveylab/STORAGE1_NA/NSD/full_brain_no_processing

  stans_thesis_repo_data: /media/harveylab/storage2/stan-thesis/data/
  mask_data_dir: mask
  freesurfer_dir: /media/harveylab/storage2/stan-thesis/data/nsddata/freesurfer

# COCO dataset paths
coco_data:
  coco_train_json_path: data/coco/instances_train2017.json
  coco_val_json_path: data/coco/instances_val2017.json
  nsd_coco_file_path: coco/nsd_coco.xlsx
  nsd_labeled_subset_path: coco/nsd_full_coco.xlsx

# Dataset creation files (Step-wise comments added)
dataset_creation:
  # Step 1: Initial subsets
  subset_non_animate: nsd_full_non_animals.xlsx
  subset_animate: nsd_full_animals_humans.xlsx

  # Step 2: Face detection -> generate positive and negative set
  subset_animate_face_unchecked: faces/faces_unchecked.xlsx
  subset_animate_non_face_unchecked: animate_nonface/animate_non_face_unchecked.xlsx

  # Step 3: Remove NaNs
  subset_animate_face_nans_removed: faces/faces_nans_removed.xlsx
  subset_animate_non_face_nans_removed: animate_nonface/animate_non_face_nans_removed.xlsx

  # Step 4: Labeled (checked labeling)
  subset_animate_face_labelled: faces/faces_labelled.xlsx
  subset_animate_non_face_labelled: animate_nonface/animate_non_face_labelled.xlsx

  # Step 5: Final dataset
  subset_animate_face_final: faces/faces_final.xlsx
  subset_animate_non_face_final: animate_nonface/animate_non_face_final.xlsx

# Face detection results path
face_detection:
  results_path: face_detection_result.json

# NSD project structure
nsd_project:
  nsd_data_dir: /media/harveylab/storage2/stan-thesis/data
  mask_subdir: mask
  label_subdir: nsddata
  conds_subdir: conditions
  nsd_subdir: NSD
  proj_dir: /media/harveylab/storage2/stan-thesis
  betas_subdir: betas

all_rois: { "LO2": 1, "LO1": 2, "hMT+/V5": 3, "OFA": 4, "?": 5, "PPA": 6, "FFA": 7, "V3A/V3B": 8, "RSC" : 9}

# all_rois_fullnames = {
#     "LO2": "Lateral Occipital area 2",
#     "LO1": "Lateral Occipital area 1",
#     "hMT+/V5": "Human Middle Temporal complex (V5)",
#     "OFA": "Occipital Face Area",
#     "?": "Unlabeled/Unspecified ROI",
#     "PPA": "Parahippocampal Place Area",
#     "FFA": "Fusiform Face Area",
#     "V3A/V3B": "Visual areas 3A and 3B",
#     "RSC": "Retrosplenial Cortex"
# }

# region_mapping = {
#     8:  {"color": "bright red",   "region": "hMT⁺ (V5)",             "confidence": "moderate"},
#     9:  {"color": "dark maroon",  "region": "pSTS face patch",      "confidence": "low"},
#     3:  {"color": "cyan",         "region": "OFA",                   "confidence": "moderate"},
#     1:  {"color": "royal blue",   "region": "FFA",                   "confidence": "high"},
#     2:  {"color": "dodger blue",  "region": "FBA",                   "confidence": "moderate"},
#     4:  {"color": "mint green",   "region": "EBA",                   "confidence": "moderate"},
#     7:  {"color": "orange",       "region": "OPA (TOS)",             "confidence": "high"},
#     6:  {"color": "yellow",       "region": "PPA",                   "confidence": "moderate"},
#     5:  {"color": "lime green",   "region": "ATFA",                  "confidence": "low"},
# }



# Subjects and ROIs to analyze
analysis:
  subjects_to_analyze: [1] # [1, 2, 3, 7]
  rois_to_analyze:
    { "LO2": 1, "LO1": 2, "hMT+/V5": 3, "OFA": 4, "?": 5, "PPA": 6, "FFA": 7, "V3A/V3B": 8, "RSC" : 9}

# Dataset validation parameters
dataset_validation:
  nsd_samples_subjects_to_check: ["1"] # ['shared', '1', ..., '8']

pipeline:
  step_1_preprocessing:
    execute_step: false

    step: 1
    extract_nsd_data: true
    subjects: [1] # Define subjects for extraction

  step_2_dataset_creation:
    execute_step: true

    download_data: false
    create_data_split: false
    face_detection: true
    generate_non_face_set: false
    generate_positive_set: false
    remove_nans: false
    label_data: false
    load_betas: false
    subjects: [1] # Subjects for dataset creation
    step: 2

  step_3_t_testing:
    execute_step: false

    t_testing: false
    subjects: [1] # Subjects for t-testing
    step: 3

    thresholds_map: [0.0, 2.0, 3.0, 4.0, 5.0]
    clipping_value: 7

  step_4_rsa_analysis:
    execute_step: true

    only_face_set: true
    distance_metric: "correlation"
    rsa_analysis: true
    subjects: [1] # Subjects for RSA
    step: 4

  step_5_gaussian_fitting:
    execute_step: true

    fit_gaussian: true
    visualize: true
    evaluate: true

    t_test_filtering: 0.0
    sigma_filtering: [0, 100]

    subjects: [1] # Subjects for Gaussian fitting
    step: 5

  overwrite_existing: false # Global overwrite flag

